name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # todos os dias
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: cmps5
          THEME: vue
          OUTPUT_DIR: profile-summary-cards

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update profile summary cards"
          file_pattern: profile-summary-cards/*
